// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var anual_calc, bimestral_calc, semestral_calc;
    $.ketchup.messages({
      required: 'Campo Obrigatório'
    });
    $.ketchup.createErrorContainer(function(form, el) {
      return $("<ul/>", {
        "class": "error-messages"
      }).insertAfter(el);
    }).addErrorMessages(function(form, el, container, messages) {
      var i, _results;
      container.html("");
      i = 0;
      _results = [];
      while (i < messages.length) {
        $("<li/>", {
          text: messages[i]
        }).appendTo(container);
        _results.push(i++);
      }
      return _results;
    }).showErrorContainer(function(form, el, container) {
      return container.slideDown("fast");
    }).hideErrorContainer(function(form, el, container) {
      return container.slideUp("fast");
    });
    $("#bimestralForm").ketchup({
      validateEvents: "blur focus keyup"
    });
    $("#semestralForm").ketchup({
      validateEvents: "blur focus keyup"
    });
    $("#anualForm").ketchup({
      validateEvents: "blur focus keyup"
    });
    bimestral_calc = function() {
      var pd, total, v1, v2, vm;
      v1 = $('#v1').val();
      v2 = $('#v2').val();
      pd = $('#pd').val();
      vm = $('#vm').val();
      total = (parseFloat(v1) + parseFloat(pd) + parseFloat(v2) + parseFloat(vm)) / 2;
      if (total < 60) {
        return alert('Olá, sua notá é ' + parseFloat(total) + ' e infelizmente você não passou.' + ' Você precisa de ' + (60 - parseFloat(total)) + ' pontos para passar');
      } else {
        return alert('Sua nota é ' + parseFloat(total) + ' parabéns, você passou !');
      }
    };
    $('#bimestral').click(function() {
      if ($('#bimestralForm').ketchup('isValid')) {
        return bimestral_calc();
      } else {
        return el.ketchup('validate');
      }
    });
    semestral_calc = function() {
      var b1, b2, total;
      b1 = $('#b1').val();
      b2 = $('#b2').val();
      total = ((parseFloat(b1) * 2) + (parseFloat(b2) * 3)) / 5;
      if (total < 60) {
        return alert('Olá, sua notá é ' + parseFloat(total) + ' e infelizmente você não passou.' + ' Você precisa de ' + (60 - parseFloat(total)) + ' pontos para passar');
      } else {
        return alert('Sua nota é ' + parseFloat(total) + ' parabéns, você passou !');
      }
    };
    $('#semestral').click(function() {
      if ($('#semestralForm').ketchup('isValid')) {
        return semestral_calc();
      } else {
        return el.ketchup('validate');
      }
    });
    anual_calc = function() {
      var b1, b2, b3, b4, total;
      b1 = $('#b1').val();
      b2 = $('#b2').val();
      b3 = $('#b3').val();
      b4 = $('#b4').val();
      total = ((parseFloat(b1) * 2) + (parseFloat(b2) * 3) + (parseFloat(b3) * 2) + (parseFloat(b4) * 3)) / 10;
      if (total < 60) {
        return alert('Olá, sua notá é ' + parseFloat(total) + ' e infelizmente você não passou.' + ' Você precisa de ' + (60 - parseFloat(total)) + ' pontos para passar');
      } else {
        return alert('Sua nota é ' + parseFloat(total) + ' parabéns, você passou !');
      }
    };
    $('#anual').click(function() {
      if ($('#anualForm').ketchup('isValid')) {
        return anual_calc();
      } else {
        return el.ketchup('validate');
      }
    });
    $('#v1').mask("99.99");
    $('#v2').mask("99.99");
    $('#pd').mask("99.99");
    $('#vm').mask("99.99");
    $('#b1').mask("99.99");
    $('#b2').mask("99.99");
    $('#b3').mask("99.99");
    return $('#b4').mask("99.99");
  });

}).call(this);
